# Runtime Parameters demo 
trigger:
- master

parameters:
- name: buildConfig
  displayName: Build Config
  type: string
  default: Release
  values:
  - Release
  - Debug

- name: vmImage
  displayName: VM Image
  type: string
  default: windows-2019
  values:
  - windows-latest
  - windows-2019
  - vs2017-win2016
  - ubuntu-latest
  - ubuntu-18.04
  - ubuntu-16.04
  - macOS-10.14
  - macOS-10.15

- name: boolVal
  displayName: second
  type: boolean
  default: true
  values:
  - true
  - false

- name: numVal
  displayName: number
  type: number
  default: 0
  values:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7

- name: jobItem
  type: job
  default:
    job: no1
    displayName: job no1
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: echo no1
      displayName: echo

- name: jobItem2
  type: job
  default:
    job: no2
    displayName: job no2
    pool:
      vmImage: 'windows-latest'
    steps:
    - script: echo no2
      displayName: echo

- name: jobItems
  type: jobList
  default: 
    - job: itemsJob1
      displayName: items job no1
      pool:
        vmImage: 'windows-latest'
      steps:
      - script: echo items job no1
        displayName: echo items no1
  values: [jobItem, jobItem2]

jobs:
- job: echo
  displayName: echo
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - script: echo ${{ parameters.buildConfig }}
    displayName: echo
  - ${{ if eq(parameters.boolVal, true) }}:
    - script: echo ${{ parameters.numVal }}
      displayName: 'echo num'

- ${{ parameters.jobItem }}
- ${{ parameters.jobItems }}